package com.cpssoft.web.test.accurate.tool;

public enum ModuleButton {
	MAIN_SIMPAN, MAIN_HAPUS, MAIN_CETAK, MAIN_HISTORI, MAIN_REKAMAN,

	TAB_HISTORY, TAB_LIST, TAB_CLOSE,

	CONTENT_TAMBAH_SALDO, CONTENT_TAMBAH_KONTAK, CONTENT_TAMBAH_DETAIL, CONTENT_RECALCULATE, CONTENT_SIMPAN,

	FOOTER_PERCENT,

	LIST_TAMBAH

	;
}
